[platformio]
default_envs = ESP32
src_dir = CommandStation-EX
lib_dir = CommandStation-EX
include_dir = CommandStation-EX
build_dir = CommandStation-EX/.pio/build

[env:ESP32]
platform = espressif32 @ 6.7.0
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_echo = yes
board_build.filesystem = littlefs
extra_scripts = pre:tools/stage_default_data.py
build_flags =
    -Wall
    -Wextra
    -std=c++17
    -DHTTP
    -DCONFIG_ASYNC_TCP_RUNNING_CORE=0
    -DCONFIG_ASYNC_TCP_USE_WDT=1
lib_deps =
    https://github.com/esphome/ESPAsyncWebServer.git
    https://github.com/esphome/AsyncTCP.git
    bblanchon/ArduinoJson@^7.3.1
