// AUTO-GENERATED by tools/prepare-demo-seed.mjs.
// Commit this file so GitHub Pages has demo seed data even when data/*.json
// is excluded from the repository.

export const demoSeedLayout = {
  "layers": [
    {
      "id": "buildings",
      "name": "Épületek",
      "visible": true,
      "locked": false,
      "elements": [
        {
          "id": "8c4fb0a-8ce3-4b52-a285-d91c8432",
          "type": "routebutton",
          "name": "element",
          "layerName": "buildings",
          "x": 8,
          "y": 12,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "label": "Route",
          "colorOn": "lime",
          "routeTurnouts": [
            {
              "turnoutId": "22d3018-1b1a-4a77-b4d8-9f74387c",
              "closed": true
            }
          ]
        },
        {
          "id": "a32300d-7eb3-4825-b2fd-b03cc8ad",
          "type": "routebutton",
          "name": "element",
          "layerName": "buildings",
          "x": 10,
          "y": 12,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "label": "Route",
          "colorOn": "lime",
          "routeTurnouts": [
            {
              "turnoutId": "22d3018-1b1a-4a77-b4d8-9f74387c",
              "closed": false
            }
          ]
        },
        {
          "id": "67621e2-2f28-478f-8780-6cc83994",
          "type": "label",
          "name": "element",
          "layerName": "buildings",
          "x": 8,
          "y": 13,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "text": "Egyenes",
          "fontSize": 12,
          "color": "#fab005",
          "alignment": "center",
          "offsetY": 0,
          "offsetX": 0
        },
        {
          "id": "fa36625-f42a-4e37-a691-8c37e07c",
          "type": "label",
          "name": "element",
          "layerName": "buildings",
          "x": 10,
          "y": 13,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "text": "Kitérő",
          "fontSize": 12,
          "color": "#ffffff",
          "alignment": "center",
          "offsetY": 0,
          "offsetX": 0
        }
      ]
    },
    {
      "id": "blocks",
      "name": "Blokkok",
      "visible": true,
      "locked": false,
      "elements": []
    },
    {
      "id": "sensors",
      "name": "Sensors",
      "visible": true,
      "locked": false,
      "elements": [
        {
          "id": "c5d6364-6ccd-4c33-a416-07666df4",
          "type": "tracksensor",
          "name": "element",
          "layerName": "sensors",
          "x": 4,
          "y": 7,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 0,
          "bg": "black",
          "fg": "white",
          "address": 180,
          "length": 200,
          "kind": 1,
          "colorOn": "#f11414",
          "colorOff": "green",
          "radius": 6
        }
      ]
    },
    {
      "id": "signals",
      "name": "Signals",
      "visible": true,
      "locked": false,
      "elements": [
        {
          "id": "d39fe15-ab04-4623-900b-8ee991e1",
          "type": "tracksignal2",
          "name": "element",
          "layerName": "signals",
          "x": 10,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 100,
          "length": 200,
          "aspect": 4,
          "outputMode": "vpin",
          "addressLength": 3,
          "dispalyAsSingleLamp": true,
          "valueGreen": 4,
          "valueRed": 1,
          "valueYellow": 2,
          "valueWhite": 8
        },
        {
          "id": "4984b2e-46d1-49c1-b14f-2294c9b2",
          "type": "tracksignal2",
          "name": "element",
          "layerName": "signals",
          "x": 7,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 180,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 110,
          "length": 200,
          "aspect": 4,
          "outputMode": "accessory",
          "addressLength": 5,
          "dispalyAsSingleLamp": true,
          "valueGreen": 1,
          "valueRed": 2,
          "valueYellow": 4,
          "valueWhite": 8
        },
        {
          "id": "cd53253-43f8-4aab-bece-eee93635",
          "type": "tracksignal2",
          "name": "element",
          "layerName": "signals",
          "x": 7,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 180,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 120,
          "length": 200,
          "aspect": 4,
          "outputMode": "accessory",
          "addressLength": 5,
          "dispalyAsSingleLamp": true,
          "valueGreen": 1,
          "valueRed": 2,
          "valueYellow": 4,
          "valueWhite": 8
        }
      ]
    },
    {
      "id": "track",
      "name": "Pálya",
      "visible": true,
      "locked": false,
      "elements": [
        {
          "id": "track1",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 10,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "22d3018-1b1a-4a77-b4d8-9f74387c",
          "type": "trackturnoutright",
          "name": "element",
          "layerName": "track",
          "x": 9,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 180,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200,
          "turnoutAddress": 20,
          "outputMode": "accessory",
          "turnoutClosedValue": true
        },
        {
          "id": "01832cb-b96f-4ee1-b3e1-f1303de8",
          "type": "trackcurve",
          "name": "element",
          "layerName": "track",
          "x": 8,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 180,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "68d596f-f762-4c76-a723-d5115d8f",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 7,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "e226104-b001-4ca0-84c1-7066bece",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 6,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "a90757e-ec60-4b3d-9f68-6ddc5df3",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 5,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "574d7c8-654f-412b-9de6-442a4dc0",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 4,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "3e20eeb-ccdc-4606-bc1e-80b5a07a",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 3,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "cada6a4-ba73-4861-b5ef-b12463b6",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 3,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "353b296-df58-40af-839e-01dfd9da",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 4,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "da32194-3c0e-47ae-a2a6-1226a661",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 5,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "295766d-e8b7-4320-9049-c8cdf7c2",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 6,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "3f905bf-0d73-4c4f-aa5c-d379c2d3",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 7,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "1d31f49-c7c4-44df-bfb7-437a4011",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 8,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "12a9ac1-a77c-4e6a-84d4-1db91a21",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 11,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "41993c1-7b12-467f-b6ec-9b5e6b40",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 12,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "3033ce6-a6c7-47d4-9b87-38dd52b4",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 13,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "c982613-11f0-428a-8e91-3db1b94d",
          "type": "trackstraight",
          "name": "element",
          "layerName": "track",
          "x": 14,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "7cd8fce-afc6-4390-a792-8700f928",
          "type": "trackend",
          "name": "element",
          "layerName": "track",
          "x": 15,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "b06b6a3-7616-4fdd-aa94-b4344fc7",
          "type": "trackend",
          "name": "element",
          "layerName": "track",
          "x": 2,
          "y": 10,
          "w": 1,
          "h": 1,
          "rotation": 180,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "07c153a-ffe4-4001-a5af-5589a079",
          "type": "trackend",
          "name": "element",
          "layerName": "track",
          "x": 2,
          "y": 9,
          "w": 1,
          "h": 1,
          "rotation": 180,
          "rotationStep": 45,
          "bg": "black",
          "fg": "white",
          "address": 0,
          "length": 200
        },
        {
          "id": "fbfb778-0119-44f0-a938-dded468d",
          "type": "button",
          "name": "element",
          "layerName": "track",
          "x": 4,
          "y": 12,
          "w": 1,
          "h": 1,
          "rotation": 0,
          "rotationStep": 0,
          "bg": "black",
          "fg": "white",
          "outputMode": "accessory",
          "behavior": "toggle",
          "pulseDurationMs": 250,
          "address": 200,
          "activeValue": true,
          "colorOn": "#fab005",
          "colorOff": "#868e96",
          "textOn": "ON",
          "textOff": "OFF"
        }
      ]
    }
  ],
  "_activeLayerId": "track",
  "gridSize": 40
} as const;

export const demoSeedLocos = [
  {
    "id": "m44-148",
    "name": "M44 148 BOBO",
    "address": 18,
    "maxSpeed": 126,
    "invert": false,
    "image": "images/bobo.png",
    "length": 120,
    "trainType": "freight",
    "functions": [
      {
        "id": "m44-f0",
        "number": 0,
        "name": "Vilagitas",
        "icon": "light",
        "momentary": false
      },
      {
        "id": "m44-f1",
        "number": 1,
        "name": "Motor",
        "icon": "engine",
        "momentary": false
      },
      {
        "id": "m44-f2",
        "number": 2,
        "name": "Kurt",
        "icon": "horn",
        "momentary": true
      },
      {
        "id": "m44-f3",
        "number": 3,
        "name": "R Kurt",
        "icon": "horn",
        "momentary": true
      },
      {
        "id": "m44-f5",
        "number": 5,
        "name": "Feny tompitas",
        "icon": "light",
        "momentary": false
      },
      {
        "id": "m44-f6",
        "number": 6,
        "name": "Tolato mod",
        "icon": "shunt",
        "momentary": false
      },
      {
        "id": "m44-f28",
        "number": 28,
        "name": "Nemitas",
        "icon": "mute",
        "momentary": false
      }
    ],
    "actions": {
      "beforeStart": [
        {
          "id": "7c22cef-1b9f-40fb-889a-0dbfcdfe",
          "type": "setFunction",
          "functionNumber": 2,
          "active": true
        },
        {
          "id": "e754263-49e9-4ae5-b791-647510de",
          "type": "wait",
          "ms": 800
        },
        {
          "id": "6a7c73a-27ec-4bf3-9244-4c76cd7f",
          "type": "setFunction",
          "functionNumber": 2,
          "active": false
        }
      ],
      "afterStart": [],
      "beforeStop": [],
      "afterStop": []
    }
  },
  {
    "id": "m62-228",
    "name": "M62 228",
    "address": 3,
    "maxSpeed": 126,
    "invert": false,
    "image": "images/szergej.png",
    "length": 174,
    "trainType": "mixed",
    "functions": [
      {
        "id": "m62-f0",
        "number": 0,
        "name": "Vilagitas",
        "icon": "light",
        "momentary": false
      },
      {
        "id": "m62-f1",
        "number": 1,
        "name": "Motor",
        "icon": "engine",
        "momentary": false
      },
      {
        "id": "m62-f2",
        "number": 2,
        "name": "Kurt",
        "icon": "horn",
        "momentary": true
      },
      {
        "id": "m62-f4",
        "number": 4,
        "name": "Sip",
        "icon": "horn",
        "momentary": true
      },
      {
        "id": "m62-f6",
        "number": 6,
        "name": "Tolato mod",
        "icon": "shunt",
        "momentary": false
      },
      {
        "id": "m62-f28",
        "number": 28,
        "name": "Nemitas",
        "icon": "mute",
        "momentary": false
      }
    ]
  },
  {
    "id": "m41-2182",
    "name": "M41 2182",
    "address": 10,
    "maxSpeed": 126,
    "invert": false,
    "image": "images/csorgo.png",
    "length": 159,
    "trainType": "passenger",
    "functions": [
      {
        "id": "m41-f0",
        "number": 0,
        "name": "Vilagitas",
        "icon": "light",
        "momentary": false
      },
      {
        "id": "m41-f1",
        "number": 1,
        "name": "Motor",
        "icon": "engine",
        "momentary": false
      },
      {
        "id": "m41-f2",
        "number": 2,
        "name": "Kurt 1",
        "icon": "horn",
        "momentary": true
      },
      {
        "id": "m41-f3",
        "number": 3,
        "name": "Kurt 2",
        "icon": "horn",
        "momentary": true
      },
      {
        "id": "m41-f6",
        "number": 6,
        "name": "Tolatas",
        "icon": "shunt",
        "momentary": false
      },
      {
        "id": "m41-f28",
        "number": 28,
        "name": "Nemitas",
        "icon": "mute",
        "momentary": false
      }
    ]
  },
  {
    "id": "traxx-480-023",
    "name": "Traxx 480 023",
    "address": 22,
    "maxSpeed": 126,
    "invert": false,
    "image": "images/traxx.png",
    "length": 189,
    "trainType": "passenger",
    "functions": [
      {
        "id": "traxx-f0",
        "number": 0,
        "name": "Vilagitas",
        "icon": "light",
        "momentary": false
      },
      {
        "id": "traxx-f1",
        "number": 1,
        "name": "Motor",
        "icon": "engine",
        "momentary": false
      }
    ]
  }
] as const;

export const demoSeedSignalRulesJsonl = "{\"kind\":\"meta\",\"version\":3,\"enabled\":true}\n{\"kind\":\"group\",\"group\":{\"id\":\"a93e67a-f384-46ac-826c-e75189b6\",\"signalId\":\"d39fe15-ab04-4623-900b-8ee991e1\",\"defaultAspect\":\"red\",\"rules\":[{\"id\":\"d84c686-b8d8-4dd8-8d63-d10a2139\",\"aspect\":\"green\",\"conditions\":[{\"id\":\"4881b2d-3e96-4c85-85aa-d0b231cd\",\"type\":\"turnout\",\"turnoutId\":\"22d3018-1b1a-4a77-b4d8-9f74387c\",\"closed\":true}]},{\"id\":\"7b290ed-0ddf-4a94-b170-27b1ce77\",\"aspect\":\"yellow\",\"conditions\":[{\"id\":\"2195c78-f508-4846-941b-23ec9d36\",\"type\":\"turnout\",\"turnoutId\":\"22d3018-1b1a-4a77-b4d8-9f74387c\",\"closed\":false}]}]}}\n{\"kind\":\"group\",\"group\":{\"id\":\"10fa7df-398b-4c43-bf4d-7e9b1e3b\",\"signalId\":\"cd53253-43f8-4aab-bece-eee93635\",\"defaultAspect\":\"red\",\"rules\":[{\"id\":\"a2ac149-b776-43d7-9f52-12c7e76e\",\"aspect\":\"green\",\"conditions\":[{\"id\":\"e3be089-fcbd-4931-8e64-1a86ef71\",\"type\":\"turnout\",\"turnoutId\":\"22d3018-1b1a-4a77-b4d8-9f74387c\",\"closed\":true}]}]}}\n{\"kind\":\"group\",\"group\":{\"id\":\"a8b7620-894f-43d2-b784-43a0c00e\",\"signalId\":\"4984b2e-46d1-49c1-b14f-2294c9b2\",\"defaultAspect\":\"red\",\"rules\":[{\"id\":\"b15a3dc-1d35-4c6e-8c1a-b8e15bcf\",\"aspect\":\"yellow\",\"conditions\":[{\"id\":\"33d7368-bdc7-4ede-8dc0-97851375\",\"type\":\"turnout\",\"turnoutId\":\"22d3018-1b1a-4a77-b4d8-9f74387c\",\"closed\":false}]}]}}\n";
